fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      ref: 'v0.5.1'
    logrotate:
      repo: 'https://github.com/yo61/puppet-logrotate.git'
      # The current forge release (1.1.1) of logrotate is not compatible with
      # the future parser. See:
      # https://github.com/rodjek/puppet-logrotate/pull/39
      ref: '499b74b577d9349e315cc27d68c8648d280fbcef'
  symlinks:
    selenium: "#{source_dir}"
